In [241]:
import numpy
from scipy.spatial.distance import cdist
from sklearn.metrics.pairwise import cosine_similarity

C:\Users\mvancl\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\mvancl\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\mvancl\AppData\Local\Programs\Python\Python37\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [475]:
target = numpy.random.randn(1,300, 100)
target

array([[[-0.26971266,  2.12064793, -0.74672078, ..., -0.22563273,
          2.1232748 , -0.03389988],
        [-1.4272729 , -0.36924639,  0.03569561, ...,  0.33463261,
          0.82953571,  0.09809499],
        [-1.13534811,  1.75561327, -0.05408585, ..., -0.26879393,
          0.456239  ,  0.04494794],
        ...,
        [ 0.71175967, -2.02950393, -0.25469894, ..., -0.15977693,
         -0.98417071,  3.01577131],
        [ 0.01530045,  0.02664978,  0.78394241, ..., -0.52960493,
         -0.27077948, -1.5445606 ],
        [-0.85157537, -1.04934668,  0.64272118, ...,  1.37009782,
          0.78757458, -0.58126957]]])

In [476]:
vectors = numpy.random.randn(10000,300,1)
vectors

array([[[ 7.54253839e-02],
        [ 1.76819810e+00],
        [ 4.99059048e-01],
        ...,
        [ 2.39567762e-04],
        [ 1.06604672e+00],
        [-6.60264155e-01]],

       [[-9.71908883e-01],
        [ 9.04825785e-02],
        [ 8.23643221e-01],
        ...,
        [-1.39015031e+00],
        [-1.27650046e+00],
        [-5.22834420e-01]],

       [[-4.67806344e-01],
        [-1.89798645e+00],
        [-1.58326396e+00],
        ...,
        [-4.78867294e-01],
        [-8.52441640e-01],
        [-4.42029496e-01]],

       ...,

       [[ 6.30047783e-01],
        [-1.10294718e+00],
        [ 5.20887231e-02],
        ...,
        [-1.23607719e+00],
        [ 1.92429515e+00],
        [ 1.98631768e+00]],

       [[ 1.64636360e-01],
        [-1.03581427e-01],
        [ 2.41621735e-01],
        ...,
        [-4.04146992e-01],
        [ 1.38981534e-01],
        [-1.10201814e+00]],

       [[ 1.55526345e+00],
        [-9.95448876e-01],
        [ 2.02399466e+00],
        ...,
        

In [478]:
tm = target.reshape((300, 100)).T
vm = vectors.reshape((10000,300))

In [259]:
%%time

res
for t in tm:
    res = cdist([t], vm, 'cosine')
res.shape

Wall time: 1min 33s


(1, 100000)

In [261]:
res[0,0]

0.9750212448515615

In [480]:
epochs = 100

In [481]:
%%time

for i in range(epochs):
    print(i)
    res2 = cdist(tm, vm, 'cosine')
res2.shape

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
Wall time: 44.5 s


(100, 10000)

In [264]:
res2[-1,0]

0.9750212448515615

In [265]:
%%time

vmn = numpy.einsum('ij,ij->i',vm,vm)
for t in tm:
    den  = numpy.sqrt(vmn*numpy.einsum('j,j',t,t))
    res3 = vm.dot(t)/den 
res3.shape

Wall time: 23 s


(100000,)

In [266]:
1-res3[0]

0.9750212448515616

In [281]:
%%time

vmn = numpy.linalg.norm(vm, axis=1)
for t in tm:
    den  = vmn*numpy.linalg.norm(t)
    res4 = vm.dot(t)/den 
res4.shape

Wall time: 22.4 s


(100000,)

In [282]:
1-res4[0]

0.9750212448515616

In [482]:
%%time

vn = numpy.linalg.norm(vectors, axis=1)
for i in range(epochs):
    print(i)
    tn = numpy.linalg.norm(target, axis=1)
    norm = vn @ tn
    dat = vm @ tm.T
    res5 = dat / norm
res5.shape

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
Wall time: 4.26 s


(10000, 100)

In [472]:
1-res5[0,-1]

0.9757589056098677

In [483]:
%%time

for i in range(epochs):
    print(i)
    res6 = cosine_similarity(vm, tm)
res6.shape

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
Wall time: 5.86 s


(10000, 100)

In [418]:
1-res6[0,0]

1.1742956638682756

In [94]:
%%time

den  = numpy.sqrt(numpy.einsum('ij,ij->i',vectors,vectors)*numpy.einsum('j,j',t,t))
res4 = vectors.dot(t)/den 
res4.shape

Wall time: 5.33 s


(10000,)

In [114]:
res[0,0]

0.9618245143565451

In [115]:
res3[-1,0]

0.9618245143565451

In [116]:
1-res2[0]

0.9618245143565451

In [224]:
a=vectors
b=target

In [225]:
a_norm = numpy.linalg.norm(a, axis=1)
display(a_norm.shape)
b_norm = numpy.linalg.norm(b, axis=1)
display(b_norm.shape)

(10000, 1)

(1, 1000)

In [226]:
norm = a_norm @ b_norm
norm.shape

(10000, 1000)

In [227]:
display(a.shape)
display(b.shape)

(10000, 300, 1)

(1, 300, 1000)

In [228]:
display(a.reshape((10000,300)).shape)
display(b.reshape((300,1000)).shape)

(10000, 300)

(300, 1000)

In [229]:
dat = a.reshape((10000,300)) @ b.reshape((300,1000))
dat.shape

(10000, 1000)

In [203]:
res5 = dat / norm
res5.shape

(10000, 1000)

In [328]:
import time
import numpy
from scipy.spatial.distance import cdist
from sklearn.metrics.pairwise import cosine_similarity

target = numpy.random.rand(100,300)
vectors = numpy.random.rand(10000,300)

start = time.time()
most_similar_sklearn = cosine_similarity(target, vectors)
print("Sklearn cosine_similarity: {} s".format(time.time()-start))
start = time.time()
most_similar_scipy = 1-cdist(target, vectors, 'cosine')
print("Scipy cdist: {} s".format(time.time()-start))
equals = numpy.allclose(most_similar_sklearn, most_similar_scipy)
print("Equal results: {}".format(equals))

Sklearn cosine_similarity: 0.05303549766540527 s
Scipy cdist: 0.44914913177490234 s
Equal results: True


In [312]:
%%time
most_similar2 = 1-cdist(target, vectors, 'cosine')

Wall time: 427 ms


In [313]:
most_similar.shape

(100, 10000)

In [316]:
most_similar[0,0]

0.7320288224385277

In [310]:
most_similar2.shape

(100, 10000)

In [317]:
most_similar2[0,0]

0.7320288224385272

In [318]:
numpy.allclose(most_similar,most_similar2)

True

In [342]:
most_similar_sklearn.shape

(100, 10000)

In [463]:
import time
import numpy

target = numpy.random.rand(100,300)
vectors = numpy.random.rand(10000,300)

most_similar_sklearn = cosine_similarity(target, vectors)

start = time.time()

t_ext = target.reshape((100,300, 1))
v_ext = vectors.T.reshape((1,300,10000))
t_norm = numpy.linalg.norm(t_ext, axis=1)
v_norm = numpy.linalg.norm(v_ext, axis=1)
norm = t_norm @ v_norm
dat = target @ vectors.T
most_similar_numpy = dat / norm

print("Numpy matmul: {} s".format(time.time()-start))
equals = numpy.allclose(most_similar_sklearn, most_similar_numpy)
print("Equal results: {}".format(equals))

Numpy matmul: 0.055016279220581055 s
Equal results: True


In [422]:
most_similar_numpy[0,0]

0.7241075476648691

In [423]:
most_similar_sklearn[0,0]

0.7276669768462649

In [453]:
target = numpy.random.randn(100, 300)
vectors = numpy.random.randn(10000,300)

In [438]:
tm = target.T.reshape((1,300, 100))
vm = vectors.reshape((10000,300,1))

In [441]:
vn = numpy.linalg.norm(vm, axis=1)
tn = numpy.linalg.norm(tm, axis=1)
norm = vn @ tn
dat = vectors @ target.T
most_similar_numpy = dat / norm
most_similar_numpy.shape

(10000, 100)

In [443]:
most_similar_sklearn = cosine_similarity(vectors, target)
most_similar_sklearn.shape

(10000, 100)

In [444]:
most_similar_numpy[0,0]

-0.00809374554066286

In [445]:
most_similar_sklearn[0,0]

-0.008093745540662844

In [454]:
tm = target.reshape((100,300, 1))
vm = vectors.T.reshape((1,300,10000))

In [455]:
tn = numpy.linalg.norm(tm, axis=1)
vn = numpy.linalg.norm(vm, axis=1)
norm = tn @ vn
dat = target @ vectors.T
most_similar_numpy = dat / norm
most_similar_numpy.shape

(100, 10000)

In [456]:
most_similar_sklearn = cosine_similarity(target, vectors)
most_similar_sklearn.shape

(100, 10000)

In [457]:
most_similar_numpy[0,0]

-0.009593478096148283

In [458]:
most_similar_sklearn[0,0]

-0.009593478096148298

In [459]:
numpy.allclose(most_similar_numpy, most_similar_sklearn)

True

In [465]:
arr = [numpy.array([1,2]), numpy.array([3,4])]
arr

[array([1, 2]), array([3, 4])]

In [467]:
numpy.reshape(arr, (1,2,2))

array([[[1, 2],
        [3, 4]]])